### ISSUE TITLE
如果我只要地图该怎么做

### ISSUE THREAD

**Issue by smalllam** [reg233/nezha-theme-world-map#4]

**Comment by reg233** [comment]
在 `assets/index-xxxxxxxx.css` 底部加入以下内容

#### 样式一

```css
.ant-collapse-item:not(:first-child){display:none}
```

#### 样式二

```css
.tabs{display:none}@media only screen and (min-width:702px){.ant-collapse{padding:4% 16px}}
```
